@startuml
skinparam monochrome true
skinparam handwritten true

actor Teacher

participant Server

actor Student

Teacher -> Server : Create lesson
Server --> Teacher : ok
|||
Student -> Server : Retrieve lessons
Server --> Student : lessons
|||
Student -> Server : Signup to lesson
Server --> Teacher : New student
...
Teacher -> Server : Start lesson
...
Server --> Student : stimulus0
...
Server --> Student : stimulus1
@enduml
